//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriesMenu
    {
        public CategoriesMenu()
        {
            this.Menu = new HashSet<Menu>();
        }
    
        public int id_category { get; set; }
        public string title_category { get; set; }
    
        public virtual ICollection<Menu> Menu { get; set; }
    }
}
