//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Orders = new HashSet<Orders>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int id_client { get; set; }
        public string name_client { get; set; }
        public string ph_numb_client { get; set; }
    
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual Regular_Clients Regular_Clients { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
