//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Orders = new HashSet<Orders>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int id_employee { get; set; }
        public string name_employee { get; set; }
        public string ph_number_emp { get; set; }
        public int post_emp_fk { get; set; }
        public string email { get; set; }
        public byte[] photo_data { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual ICollection<Orders> Orders { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
