//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public Menu()
        {
            this.Order_details = new HashSet<Order_details>();
        }
    
        public int id_menu_item { get; set; }
        public string item_name { get; set; }
        public int id_category_fk { get; set; }
        public decimal cost_item { get; set; }
    
        public virtual CategoriesMenu CategoriesMenu { get; set; }
        public virtual ICollection<Order_details> Order_details { get; set; }
    }
}
