//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cafe_barEntities1 : DbContext
    {
        public cafe_barEntities1()
            : base("name=cafe_barEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Autorization> Autorization { get; set; }
        public DbSet<CategoriesMenu> CategoriesMenu { get; set; }
        public DbSet<Clients> Clients { get; set; }
        public DbSet<Employees> Employees { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Order_details> Order_details { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Post> Post { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<Regular_Clients> Regular_Clients { get; set; }
    }
}
