//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int id_order_details { get; set; }
        public int id_order_fk { get; set; }
        public int id_menu_item_fk { get; set; }
        public short quantity { get; set; }
        public decimal unit_price { get; set; }
        public Nullable<decimal> subtotal { get; set; }
    
        public virtual Menu Menu { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
