//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_details = new HashSet<Order_details>();
        }
    
        public int id_order { get; set; }
        public int id_cli_fk { get; set; }
        public int id_emp_fk { get; set; }
        public System.DateTime order_date { get; set; }
        public decimal totalAmount { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Order_details> Order_details { get; set; }
    }
}
