//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public Post()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int id_post { get; set; }
        public string title_post { get; set; }
        public byte accessLevel { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
