//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace material_design
{
    using System;
    using System.Collections.Generic;
    
    public partial class Regular_Clients
    {
        public int id_reg_client_fk { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> total_spent { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
